config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :pages
  resources :movies

  get 'movies_search' => 'movies#search'
  post 'unwatched_movie' => 'movies#unwatched'
  post 'watched_movie' => 'movies#watched'

  get 'users/:id/friends' => 'users#friends', as: 'friends'

  root 'welcome#index'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get]
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_authentication

  def show
    @movie = Movie.get_by_id(params[:id])
  end

  def search
    @movies = Movie.search_by_string(params[:search][:search_string])
    render :search
  end

  def watched
    @movie = current_or_new_movie(params[:format])
    @status = current_or_new_status(@movie)

    @status.update_attribute(:watched, true)

    flash[:success] = "You have successfully watched a movie!"
    redirect_to movie_path(@movie.api_id)
  end

  def unwatched
    @movie = current_or_new_movie(params[:format])
    @status = current_or_new_status(@movie)

    @status.update_attribute(:watched, false)

    flash[:success] = "You want to watch a movie!"
    redirect_to movie_path(@movie.api_id)
  end

  private
  def current_or_new_movie(id)
    @movie = Movie.find_by_api_id(id)

    if @movie.nil?
      @api_movie = Movie.get_by_id(id)
      @movie = Movie.new
      @movie.api_id = id
      @movie.title = @api_movie["title"]
      @movie.thumbnail = @api_movie["thumbnail"]
      @movie.save!
    end

    @movie
  end

  def current_or_new_status(movie)
    @status = current_user.statuses.find_by_movie_id(movie)

    if @status.nil?
      @status = Status.new
      @status.user = current_user
      @status.movie = movie
      @status.save!
    end

    @status
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/search.html.erb
<div class="container-fluid">
  <h1 class="text-center">Your Search Results</h1>
  <hr />
  <% if !@movies.nil? %>
    <% @movies.in_groups_of(3).each do |movie_slices| %>
      <div class="row">
        <% movie_slices.each do |movie| %>
          <% if movie %>
            <div class="col-md-4">
              <h2 class="text-center"><%= link_to movie["title"], movie_path(movie["id"]) %></h2>
              <hr />
              <p><%= movie["short_description"] %></p>
              <p>Rating: <%= movie["rating"] %></p>
              <p><%= link_to "I watched this!", watched_movie_path(movie["id"]), method: :post unless current_user.watched?(movie["id"]) || current_user.unwatched?(movie["id"]) %></p>
              <p><%= link_to "I want to watch this!", unwatched_movie_path(movie["id"]), method: :post unless current_user.watched?(movie["id"]) || current_user.unwatched?(movie["id"]) %></p>
              <p><%= link_to "I finally got around to watching this one!", watched_movie_path(movie["id"]), method: :post if current_user.unwatched?(movie["id"]) %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="row">
      <div class="col-md-12 text-center">
        <p>Looks like there are no movies! Sorry! Try another search phrase.</p>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div style="text-align: center">
  <div class="container-fluid">
    <div class="media">
      <div class="media-left">
        <img class="media-object" src="<%= @movie["thumbnail"] %>" alt="movie poster" height="400">
        <p><%= link_to "I watched this!", watched_movie_path(@movie["id"]), method: :post unless current_user.watched?(@movie["id"]) || current_user.unwatched?(@movie["id"]) %></p>
        <p><%= link_to "I want to watch this!", unwatched_movie_path(@movie["id"]), method: :post unless current_user.watched?(@movie["id"]) || current_user.unwatched?(@movie["id"]) %></p>
        <p><%= link_to "I finally got around to watching this one!", watched_movie_path(@movie["id"]), method: :post if current_user.unwatched?(@movie["id"]) %></p>
      </div>
    <div class="media-body">
      <h4 class="media-heading" style="text-align:left"><%= @movie["title"] %></h4>
      <div class="row">
        <div class="col-md-4" style="padding-right:0">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Info</h3>
            </div>
            <div class="panel-body" style="padding-left:0;height:15em;overflow-y:scroll">
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <td>Rating</td>
                    <td><%= @movie["rating"] %></td>
                  </tr>
                  <tr>
                    <td>Genre</td>
                    <td><%= @movie["genre"] %></td>
                  </tr>
                  <tr>
                    <td>Runtime</td>
                    <td><%= @movie["runtime"] %></td>
                  </tr>
                  <tr>
                    <td>Release Date</td>
                    <td><%= @movie["release_date"] %></td>
                  </tr>
                  <tr>
                    <td>Cast</td>
                    <td><%= @movie["cast"] %></td>
                  </tr>
                 </table>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Description</h3>
              </div>
              <div class="panel-body" style="padding-left:0;height:15em;overflow-y:scroll">
                <%= @movie["short_description"] %>
              </div>
            </div>
          </div>
        </div>
        <br>
        <% unless @movie["related"].nil? %>
          <div class="col-md-12" style="padding:0">
            <div class="panel panel-info">
              <div class="panel-heading">
                <h3 class="panel-title">Related Titles</h3>
              </div>
              <div class="panel-body" style="padding-left:0;">
                <% @movie["related"].in_groups_of(7).first.each do |related| %>
                  <% unless related.nil? %>
                    <a href="<%= movie_path(related["id"]) %>"><img src="<%= related["thumbnail"] %>" style="height:15em"></a>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>