config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :pages
  resources :movies

  get 'movies_search' => 'movies#search'
  post 'unwatched_movie' => 'movies#unwatched'
  post 'watched_movie' => 'movies#watched'

  get 'users/:id/friends' => 'users#friends', as: 'friends'

  root 'welcome#index'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :statuses, dependent: :destroy
  has_many :movies, through: :statuses

  has_many :services

  def shared_unwatched_movies
    @movies_and_friends = []
    @friends = self.friends

    if !@friends.empty?
      @s_movies = self.unwatched_movies

      @friends.each do |friend|
        @f_movies = friend.unwatched_movies

        @s_movies.each do |movie1|
          @f_movies.each do |movie2|
            if movie1 == movie2
              @movies_and_friends.push({ "movie" => movie1, "friend" => friend.name })
            end
          end
        end
      end
    end

    @movies_and_friends
  end

  def watched_movies
    @movies = []
    self.statuses.where(watched: true).each do |status|
      @movies << status.movie
    end
    @movies
  end

  def unwatched_movies
    @movies = []
    self.statuses.where(watched: false).each do |status|
      @movies << status.movie
    end
    @movies
  end

  def friends
    @facebook = User.koala(self.id)
    @friends = []

    if @facebook["friends"]
      @facebook["friends"]["data"].each do |friend|
        @user = User.find_by_facebook_id(friend["id"])
        @friends << @user unless @user.nil?
      end

      @friends
    else
      nil
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.token = auth['credentials']['token']
      facebook = Koala::Facebook::API.new(user.token)
      if auth['info']
        user.facebook_id = facebook.get_object("me?fields=friends")['id'] || ""
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email'] || ""
      end
    end
  end

  def self.koala(id)
    facebook = Koala::Facebook::API.new(User.find(id).token)
    facebook.get_object("me?fields=friends")
  end

  def watched?(movie_api_id)
    @status = self.statuses.where(movie: Movie.find_by_api_id(movie_api_id))
    if @status.exists?
      @status.first.watched
    else
      false
    end
  end

  def unwatched?(movie_api_id)
    @status = self.statuses.where(movie: Movie.find_by_api_id(movie_api_id))
    if @status.exists?
      !@status.first.watched
    else
      false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_authentication

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def friends
    @user = User.find(params[:id])
    @friends = @user.friends
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/friends.html.erb
<div class="container">
  <h3>Friends List</h3>
  <hr />
  <% if @friends.empty? %>
    <p>Looks like you don't have any friends here yet. Tell them to join!</p>
  <% else %>
    <% @friends.each do |friend| %>
      <h3><%= link_to friend.name, friend %></h3>
      <hr />
    <% end %>
  <% end %>
 </div>

app/views/users/show.html.erb
<div class="container-fluid">
  <h1 class="text-center"><%= @user.name %></h1>
  <hr />
  <div class="row">
    <div class="col-md-12">
      <h2 class="text-center">Movies Watched</h2>
      <hr />
      <% if @user.watched_movies.empty? %>
        <p class="text-center">Looks like there you haven't watched any movies yet! Sorry!</p>
      <% else %>
        <% @user.watched_movies.in_groups_of(4).each do |movie_slices| %>
          <div class="row">
            <% movie_slices.each do |movie| %>
              <% if movie %>
                <div class="col-md-3">
                 <hr />
                  <a href="<%= movie_path(movie.api_id) %>"><img style="margin: 0 auto" class="media-object" src="<%= movie.thumbnail %>" alt="movie poster" height="400"></a>
                  <h3 class="text-center"><%= link_to "#{truncate movie.title, :length => 32, :separator => /\w/, :omission => "..."}".html_safe, movie_path(movie.api_id) %></h3>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-12">
      <h2 class="text-center">Movies to Watch</h2>
      <hr />
      <% if @user.unwatched_movies.empty? %>
        <p class="text-center">Looks like there aren't any movies to watch! Sorry!</p>
      <% else %>
        <% @user.unwatched_movies.in_groups_of(4).each do |movie_slices| %>
          <div class="row">
            <% movie_slices.each do |movie| %>
              <% if movie %>
                <div class="col-md-3">
                  <hr />
                  <a href="<%= movie_path(movie.api_id) %>"><img style="margin: 0 auto" class="media-object" src="<%= movie.thumbnail %>" alt="movie poster" height ="400"></a>
                  <h3 class="text-center"><%= link_to "#{truncate movie.title, :length => 32, :separator => /\w/, :omission => "..."}".html_safe, movie_path(movie.api_id) %></h3>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% unless @user.shared_unwatched_movies.empty? %>
    <hr style="padding-top: 20px" />
    <h2 class="text-center">Watch these movies with your friends!</h2>
    <hr />
    <div class="row" style="padding-bottom: 20px">
      <% @user.shared_unwatched_movies.each do |movie| %>
        <div class="col-md-3">
          <h3 class="text-center"><%= truncate movie["friend"], :length => 20, :separator => /\w/, :omission => "..." %></h3>
          <hr />
          <a href="<%= movie_path(movie["movie"].api_id) %>"><img style="margin: 0 auto" class="media-object" src="<%= movie["movie"].thumbnail %>" alt="movie poster" height="400"></a>
        </div>
      <% end %>
    </div>
  <% end %>
</div>