config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :pages
  resources :movies

  get 'movies_search' => 'movies#search'
  post 'unwatched_movie' => 'movies#unwatched'
  post 'watched_movie' => 'movies#watched'

  get 'users/:id/friends' => 'users#friends', as: 'friends'

  root 'welcome#index'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get]
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieBase</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 70px">
	<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user %>
        <%= link_to "MovieBase", current_user, class: "navbar-brand" %>
      <% else %>
        <%= link_to "MovieBase", root_path, class: "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <%= simple_form_for :search,  url: movies_search_path , :method => :get, html: { class: "navbar-form navbar-left" } do |f| %>
          <%= f.input :search_string, placeholder: "Type a movie name...", label: false %>
          <%= f.submit "Search", class: "btn btn-default" %>
        <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if session[:user_id] %>
          <li class="dropdown">
      			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        			<%= current_user.name %>
        			<span class="caret"></span>
      			</a>
      			<ul class="dropdown-menu">
          		<li><%= link_to "Friends", friends_path(current_user.id) %></li>
          		<li role="separator" class="divider"></li>
          		<li><%= link_to "Sign out", signout_path, method: :post %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign In with facebook", signin_path, method: :get %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in" >
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

<%= yield %>

</body>
</html>